/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Avatar = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "avatar.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type LeftRightContent = {
  _type: "leftRightContent";
  title?: string;
  description?: string;
  leftContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  rightContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Testimonials = {
  _type: "testimonials";
  title?: string;
  testimonials: Array<{
    quote: string;
    author: string;
    role?: string;
    company?: string;
    avatar?: Avatar;
    _key: string;
  }>;
};

export type StatsSection = {
  _type: "statsSection";
  title?: string;
  layout?: "2-column" | "3-column" | "4-column";
  stats: Array<{
    value: string;
    label: string;
    description?: string;
    _key: string;
  }>;
};

export type FaqSection = {
  _type: "faqSection";
  title?: string;
  faqs: Array<{
    question: string;
    answer: RichText;
    _key: string;
  }>;
};

export type CtaSection = {
  _type: "ctaSection";
  heading: string;
  description?: string;
  primaryButton: Link;
  secondaryButton?: Link;
  backgroundVariant?: "neutral" | "accent" | "gradient";
};

export type TextMedia = {
  _type: "textMedia";
  heading: string;
  content: RichText;
  media: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  mediaPosition?: "left" | "right";
  reverse?: boolean;
};

export type Features = {
  _type: "features";
  title?: string;
  description?: string;
  layout?: "2-column" | "3-column";
  features: Array<{
    icon?: string;
    title: string;
    description: string;
    _key: string;
  }>;
};

export type Hero = {
  _type: "hero";
  headline: string;
  subtext?: string;
  primaryCta?: Link;
  secondaryCta?: Link;
  media?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  variant?: "centered" | "left-aligned";
  backgroundVariant?: "light" | "dark" | "gradient";
};

export type PromoBanner = {
  _id: string;
  _type: "promoBanner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  enabled?: boolean;
  headline: string;
  subtext?: string;
  ctaText?: string;
  ctaUrl?: string;
  startDate?: string;
  endDate?: string;
};

export type MaintenanceBanner = {
  _id: string;
  _type: "maintenanceBanner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  enabled?: boolean;
  message: string;
  severity: "info" | "warning" | "error";
  scheduledStart?: string;
  scheduledEnd?: string;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  branding?: {
    companyName: string;
    tagline?: string;
    logo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
  };
  sections?: Array<{
    heading: string;
    links?: Array<
      {
        _key: string;
      } & Link
    >;
    _type: "footerSection";
    _key: string;
  }>;
  socialLinks?: Array<{
    platform:
      | "twitter"
      | "github"
      | "linkedin"
      | "youtube"
      | "discord"
      | "slack"
      | "facebook"
      | "instagram";
    url: string;
    ariaLabel?: string;
    _type: "socialLink";
    _key: string;
  }>;
  copyrightText?: string;
  legalLinks?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  logo?: {
    text?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
  };
  navItems?: Array<
    | {
        link?: Link;
        _type: "navLink";
        _key: string;
      }
    | {
        title: string;
        columns?: Array<{
          heading?: string;
          links?: Array<
            {
              _key: string;
            } & Link
          >;
          _type: "column";
          _key: string;
        }>;
        _type: "megaNav";
        _key: string;
      }
  >;
  ctaButton?: Link;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type HomeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "home";
};

export type Link = {
  _type: "link";
  text: string;
  linkType: "internal" | "external";
  internalLink?: PageReference | HomeReference;
  externalUrl?: string;
  openInNewTab?: boolean;
  ariaLabel?: string;
};

export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  from: string;
  to: string;
  type: "internal" | "external";
  permanent?: boolean;
};

export type Cta = {
  _type: "cta";
  title?: string;
  description?: string;
  buttons: Array<{
    link: Link;
    variant?: "primary" | "secondary" | "outline";
    _key: string;
  }>;
  alignment?: "left" | "center" | "right";
  size?: "small" | "medium" | "large";
  style?: "none" | "subtle" | "accent" | "card";
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  pageSections?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Features)
    | ({
        _key: string;
      } & TextMedia)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & CtaSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & StatsSection)
    | ({
        _key: string;
      } & Testimonials)
  >;
  seo?: Seo;
  openGraph?: OpenGraph;
};

export type OpenGraph = {
  _type: "openGraph";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
  hideFromLists?: boolean;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  pageSections?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Features)
    | ({
        _key: string;
      } & TextMedia)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & CtaSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & StatsSection)
    | ({
        _key: string;
      } & Testimonials)
  >;
  seo?: Seo;
  openGraph?: OpenGraph;
};

export type BlogReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blog";
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "number" | "bullet";
      markDefs?: Array<
        | {
            href: string;
            openInNewTab?: boolean;
            _type: "link";
            _key: string;
          }
        | {
            reference: BlogReference;
            _type: "internalLink";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type NestedModalTestRichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & NestedModalLevel1)
>;

export type NestedModalLevel3 = {
  _type: "nestedModalLevel3";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type NestedModalLevel2 = {
  _type: "nestedModalLevel2";
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & NestedModalLevel3)
  >;
};

export type NestedModalLevel1 = {
  _type: "nestedModalLevel1";
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & NestedModalLevel2)
  >;
};

export type WorkflowStatus =
  | "draft"
  | "in-review"
  | "approved"
  | "published"
  | "rejected";

export type WorkflowMetadata = {
  _type: "workflowMetadata";
  workflowStatus?: WorkflowStatus;
  submittedAt?: string;
  submittedBy?: string;
  approvedAt?: string;
  approvedBy?: string;
  rejectionReason?: string;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  slug: Slug;
  publishedAt: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content: RichText;
  nestedModalTestRichText?: NestedModalTestRichText;
  seo?: Seo;
  openGraph?: OpenGraph;
};

export type SanityVideoMetadataPlayback = {
  _type: "sanity.videoMetadata.playback";
  policy?: string;
};

export type SanityVideoMetadata = {
  _type: "sanity.videoMetadata";
  duration?: number;
  framerate?: number;
  aspectRatio?: number;
  hasAudio?: boolean;
  codec?: string;
  bitrate?: number;
};

export type SanityVideoAsset = {
  _id: string;
  _type: "sanity.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  creditLine?: string;
  metadata?: SanityVideoMetadata;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
};

export type SanityVideo = {
  _type: "sanity.video";
  asset?: unknown;
  media?: unknown;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Avatar
  | LeftRightContent
  | Testimonials
  | StatsSection
  | FaqSection
  | CtaSection
  | TextMedia
  | Features
  | Hero
  | PromoBanner
  | MaintenanceBanner
  | Footer
  | SanityImageCrop
  | SanityImageHotspot
  | Navigation
  | PageReference
  | HomeReference
  | Link
  | Redirect
  | Cta
  | Home
  | OpenGraph
  | Seo
  | Page
  | BlogReference
  | RichText
  | Slug
  | NestedModalTestRichText
  | NestedModalLevel3
  | NestedModalLevel2
  | NestedModalLevel1
  | WorkflowStatus
  | WorkflowMetadata
  | Blog
  | SanityVideoMetadataPlayback
  | SanityVideoMetadata
  | SanityVideoAsset
  | SanityVideo
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;
